name: YangYang Code Review (YCR)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: yang-code-review
        uses: yangyang-research/yang-code-review@v1.0.12
        with:
          X_YANG_API_TOKEN: ${{ secrets.X_YANG_API_TOKEN }}
          MODEL_NAME: 'anthropic_claude_sonet_4_5'
          MODEL_TEMPERATURE: 0.7
          GITHUB_TOKEN: ${{ github.token }}

